#!/usr/bin/env bash
# my-browser-rust-chromium — build engine.
#
# MVP strategy: build the real upstream cef-rs `cefsimple` example INSIDE its own
# workspace (where its workspace-deps resolve and `export-cef-dir` fetches the
# matching CEF). That gives a proven-good Rust + real-Chromium (BoringSSL) binary
# — the clean-fingerprint MVP — without standalone dependency surgery. We fork /
# customize (start URL, chrome bar, keybinds) on top of this baseline next.
#
# Data-driven: cef-rs repo + ref live in build.json (cef_rs.repo / cef_rs.ref).
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST="$HERE/dist"; WORK="$HERE/.build"
NAME="my-browser-rust-chromium"; TAG="${NAME}-latest"; TARBALL="${NAME}-linux-x86_64.tar.gz"

REPO="$(jq -r '.cef_rs.repo' "$HERE/build.json")"
REF="$(jq -r '.cef_rs.ref'  "$HERE/build.json")"
EXAMPLE_DIR="$(jq -r '.cef_rs.example_dir' "$HERE/build.json")"
EXAMPLE_PKG="$(jq -r '.cef_rs.example_pkg' "$HERE/build.json")"
CEF_DIR="$WORK/cef"; SRC="$WORK/cef-rs"

_fetch() {   # clone cef-rs @ ref + export the matching CEF into $CEF_DIR
  rm -rf "$SRC"; mkdir -p "$WORK"
  git clone --depth 1 --branch "$REF" "$REPO" "$SRC" 2>/dev/null || git clone --depth 1 "$REPO" "$SRC"
  ( cd "$SRC" && cargo run -p export-cef-dir -- --force "$CEF_DIR" )
}
_overlay() {   # our fork lives as full-file overrides in src/overlay/, layered over
               # the cloned cefsimple before building. Robust (no patch-context drift).
  [ -d "$HERE/src/overlay" ] && command cp -rf "$HERE/src/overlay/." "$SRC/examples/$EXAMPLE_DIR/" && echo "overlay applied"
  return 0
}
_build() { _overlay; export CEF_PATH="$CEF_DIR" LD_LIBRARY_PATH="$CEF_DIR:${LD_LIBRARY_PATH:-}"
  ( cd "$SRC" && cargo build -p "$EXAMPLE_PKG" --release ) ; }

_shell_data() {   # bake 2_configs/*.json -> shell/data.js. jq emits JSON, so there is no
                  # hand-rolled quoting and no sed/awk substitution hazard with & or $.
  local out="$1"
  { echo "// GENERATED by build.sh from 2_configs/*.json — do not edit by hand."
    printf 'window.MYDATA = '
    jq -n \
      --slurpfile mybar    "$HERE/2_configs/mybar.json" \
      --slurpfile plugins  "$HERE/2_configs/plugins.json" \
      --slurpfile keys     "$HERE/2_configs/keybindings.json" \
      --slurpfile settings "$HERE/2_configs/settings.json" \
      --slurpfile engines  "$HERE/2_configs/search-engines.json" \
      -f "$HERE/2_configs/shell-data.jq"
    echo ";"
  } > "$out"
  echo "generated $out"
}

cmd="${1:-help}"
case "$cmd" in
  fetch)   _fetch ;;
  build)   [ -d "$SRC" ] || _fetch; _build ;;
  run)     "$0" build; CEF_PATH="$CEF_DIR" LD_LIBRARY_PATH="$CEF_DIR" "$SRC/target/release/$EXAMPLE_PKG" "${2:-}" ;;
  test)    # unit tests for the pure winit->CEF input translation (src/overlay/input.rs).
           # CI is the only compiler here, so this is where the input layer actually
           # gets exercised -- there is no local cargo.
    [ -d "$SRC" ] || _fetch; _overlay
    export CEF_PATH="$CEF_DIR" LD_LIBRARY_PATH="$CEF_DIR:${LD_LIBRARY_PATH:-}"
    ( cd "$SRC" && cargo test -p "$EXAMPLE_PKG" --release ) ;;

  nix-hash)  # refresh the hash src/nix/package.nix pins for the published tarball.
             # Streams straight into sha256sum: the artifact is ~366MB and this box
             # runs near-full, so nothing is written to disk or the nix store.
    url="https://github.com/diegonmarcos/cloud-u-linux/releases/download/$TAG/$TARBALL"
    echo "hashing $url ..." >&2
    hex="$(curl -sfL "$url" | sha256sum | cut -d' ' -f1)"
    [ -n "$hex" ] || { echo "nix-hash: download failed" >&2; exit 1; }
    sri="$(nix hash convert --hash-algo sha256 --to sri "$hex" 2>/dev/null \
           || nix hash to-sri --type sha256 "$hex")"
    printf '# GENERATED by `build.sh nix-hash` — sha256 of the published %s.\n"%s"\n' \
      "$TARBALL" "$sri" > "$HERE/src/nix/tarball-hash.nix"
    echo "wrote src/nix/tarball-hash.nix = $sri" ;;

  check)   # render the shell in a real Chromium and assert it came up. Not a build:
           # no cargo, no CEF. Catches contract drift between index.html/shell.js/
           # pages.js/data.js, which is the failure mode that costs a CI round trip.
    tmp="$(mktemp -d)"; cp "$HERE"/2_configs/shell/. "$tmp" -r
    _shell_data "$tmp/data.js"
    bin="$(command -v chromium || command -v brave || command -v google-chrome-stable || true)"
    [ -n "$bin" ] || { echo "check: no chromium-family browser on PATH; skipped"; exit 0; }
    dom="$("$bin" --headless --disable-gpu --no-sandbox --virtual-time-budget=5000 \
             --dump-dom "file://$tmp/index.html" 2>/dev/null)"
    fail=0
    for want in 'id="mybar"' 'id="pinbar"' 'id="tabbar"' 'id="statusbar"' 'class="tab'; do
      case "$dom" in *"$want"*) ;; *) echo "check: MISSING $want"; fail=1 ;; esac
    done

    # Rows rendering is not enough: the six internal pages are separate renderers
    # and were once wired to nothing at all while the shell still looked fine.
    # Drive each one and assert it produced real content.
    cat >> "$tmp/index.html" <<'PROBE'
<div id="__probe"></div>
<script>window.addEventListener('load',function(){setTimeout(function(){
  var out=[], names=(window.PAGES&&PAGES.list)?PAGES.list():[];
  names.forEach(function(n){ try { SHELL.showPage(n);
    var b=document.getElementById('pages-body');
    out.push(n+':'+((b&&b.textContent.trim().length)||0));
  } catch(e){ out.push(n+':ERR'); } });
  document.getElementById('__probe').textContent=out.join(' ');
},400);});</script>
PROBE
    pdom="$("$bin" --headless --disable-gpu --no-sandbox --virtual-time-budget=6000 \
              --dump-dom "file://$tmp/index.html" 2>/dev/null)"
    probe="$(printf '%s' "$pdom" | sed -n 's/.*id="__probe"[^>]*>\([^<]*\)<.*/\1/p')"
    if [ -z "$probe" ]; then
      echo "check: internal-page probe produced nothing"; fail=1
    else
      echo "check: pages -> $probe"
      for pair in $probe; do
        n="${pair%%:*}"; len="${pair##*:}"
        case "$len" in ''|*[!0-9]*) echo "check: page $n FAILED"; fail=1 ;;
          *) [ "$len" -lt 20 ] && { echo "check: page $n rendered only $len chars"; fail=1; } ;;
        esac
      done
    fi
    rm -rf "$tmp"
    [ "$fail" = 0 ] && echo "check: shell renders (rows, a tab, and all internal pages)" || exit 1 ;;

  clean)   rm -rf "$WORK" "$DIST" ;;

  release) "$0" build
    mkdir -p "$DIST/bundle"
    cp "$SRC/target/release/$EXAMPLE_PKG" "$DIST/bundle/$NAME"
    cp -r "$CEF_DIR"/. "$DIST/bundle/" 2>/dev/null || true   # libcef.so + resources for a portable run
    # baked homepage (copied from qute's dashboard → 2_configs/, committed)
    cp "$HERE/2_configs/my-browser-chromium-homepage.html" "$DIST/bundle/" 2>/dev/null || true
    # browser chrome shell (MyBar / PinBar / tabs / statusbar / cmdline / internal pages).
    # It is the real UI; the homepage above is just what the first tab opens.
    mkdir -p "$DIST/bundle/shell"
    cp "$HERE"/2_configs/shell/*.html "$HERE"/2_configs/shell/*.css "$HERE"/2_configs/shell/*.js "$DIST/bundle/shell/"
    _shell_data "$DIST/bundle/shell/data.js"
    # launcher: sets CEF paths + opens the baked homepage (src/overlay parses --url=)
    cat > "$DIST/bundle/my-browser" <<'LAUNCH'
#!/usr/bin/env bash
HERE="$(cd "$(dirname "$0")" && pwd)"
export CEF_PATH="$HERE" LD_LIBRARY_PATH="$HERE"
# Upstream's osr example hardcoded wgpu Backends::VULKAN and this bundle ships
# no Vulkan ICD, so the loader found no adapter and the Rust side panicked with
# NoAdapter before a window appeared -- CEF itself was fine.
# src/overlay now asks for VULKAN|GL and honours WGPU_BACKEND, so GL is a real
# fallback and this is no longer load-bearing. Kept as belt-and-braces: point
# the loader at the host's ICDs so Vulkan still wins where a driver exists.
# ponytail: delete this block if it ever gets in the way -- GL covers it.
if [ -z "${VK_ICD_FILENAMES:-}" ] && [ -z "${VK_DRIVER_FILES:-}" ]; then
  for _d in /run/opengl-driver/share/vulkan/icd.d /usr/share/vulkan/icd.d; do
    [ -d "$_d" ] || continue
    _icd="$(ls "$_d"/*.json 2>/dev/null | tr '\n' ':' | sed 's/:$//')"
    [ -n "$_icd" ] && export VK_ICD_FILENAMES="$_icd" && break
  done
fi
# The shell IS the browser chrome, so it always stays the loaded document. A URL
# argument (xdg-open, a .desktop %U, `my-browser https://...`) must therefore be
# handed TO the shell to open in a tab, not swapped in for it -- passing it as
# --url would replace the whole UI with a bare page.
# base64 rather than percent-encoding: it sidesteps the entire quoting/escaping
# class (fragments, &, spaces, non-ASCII) with one command on each side.
SHELL_URL="file://$HERE/shell/index.html"
case "${1:-}" in
  ""|-*) ;;                                   # no URL, or a switch meant for CEF
  *) SHELL_URL="$SHELL_URL#open=$(printf %s "$1" | base64 -w0)"; shift ;;
esac
exec "$HERE/my-browser-rust-chromium" --url="$SHELL_URL" "$@"
LAUNCH
    chmod +x "$DIST/bundle/my-browser"
    tar -C "$DIST/bundle" -czf "$DIST/$TARBALL" .
    echo "staged $DIST/$TARBALL" ;;

  gh-release)
    gh release view "$TAG" >/dev/null 2>&1 \
      || gh release create "$TAG" --title "$NAME (rolling)" --notes "Rust + real-Chromium (CEF) MVP — upstream cefsimple baseline"
    gh release upload "$TAG" "$DIST/$TARBALL" --clobber ;;

  ghcr-push)   # oras rejects absolute paths → push from inside $DIST with a relative name
    ( cd "$DIST" && oras push "ghcr.io/diegonmarcos/${NAME}:latest" "${TARBALL}:application/gzip" ) ;;

  install)   # user-level install: bundle + icon + .desktop. No sudo, no system paths.
    PREFIX="${PREFIX:-$HOME/.local/share/$NAME}"
    APPS="$HOME/.local/share/applications"
    ICONS="$HOME/.local/share/icons/hicolor/scalable/apps"
    mkdir -p "$PREFIX" "$APPS" "$ICONS"
    tb="$DIST/$TARBALL"
    if [ ! -f "$tb" ]; then   # no local stage (local builds are not how this ships) -> take the rolling release
      tmp="$(mktemp -d)"; gh release download "$TAG" -D "$tmp" --clobber; tb="$tmp/$TARBALL"
    fi
    tar -xzf "$tb" -C "$PREFIX"
    chmod +x "$PREFIX/my-browser" "$PREFIX/$NAME"
    cp "$HERE/2_configs/$NAME.svg" "$ICONS/$NAME.svg"
    # awk, not sed: a substituted path containing & would be eaten by sed's replacement syntax
    awk -v exec_path="$PREFIX/my-browser" '{ gsub(/@EXEC@/, exec_path); print }' \
      "$HERE/2_configs/$NAME.desktop" > "$APPS/$NAME.desktop"
    command -v update-desktop-database >/dev/null && update-desktop-database "$APPS" 2>/dev/null || true
    command -v gtk-update-icon-cache  >/dev/null && gtk-update-icon-cache -qtf "$HOME/.local/share/icons/hicolor" 2>/dev/null || true
    echo "installed -> $PREFIX"; echo "desktop entry -> $APPS/$NAME.desktop" ;;

  uninstall) # exact inverse of install, so trying this out is reversible
    PREFIX="${PREFIX:-$HOME/.local/share/$NAME}"
    rm -rf "$PREFIX"
    rm -f "$HOME/.local/share/applications/$NAME.desktop"
    rm -f "$HOME/.local/share/icons/hicolor/scalable/apps/$NAME.svg"
    echo "removed $PREFIX + desktop entry + icon" ;;

  ship)    "$0" release && "$0" gh-release && "$0" ghcr-push ;;
  help|*)  echo "usage: build.sh {fetch|build|run [URL]|release|gh-release|ghcr-push|ship|install|uninstall|clean}" ;;
esac
