// my-konsole-dash — ratatui TUI dashboards, one per subcommand. Renders in a
// my-konsole pane, over SSH, or on a bare TTY (no webview). Ports cloud-terminal's
// 7 dashboards to terminal graphics.
mod ui;
mod frame;
mod dashboards;

use dashboards::*;

fn main() -> std::io::Result<()> {
    let name = std::env::args().nth(1).unwrap_or_else(|| "monitor".into());

    // Not a dashboard: it writes the files the monitor's E key writes and
    // exits, so the report can be regenerated by cron, by a hook, or by
    // anyone who wants the page refreshed without opening a TUI.
    // The terminal as HTML, for a caller that has a WebView and no terminal.
    // This is what the phone app runs over its ssh channel each refresh: one
    // short command in, one screen out, and no layout logic on the other side.
    if name == "tui" {
        let arg = |n: usize, d: u16| {
            std::env::args().nth(n).and_then(|x| x.parse().ok()).unwrap_or(d)
        };
        match monitor::tui_at(arg(2, 200), arg(3, 64)) {
            Ok(html) => println!("{html}"),
            Err(e) => {
                eprintln!("my-konsole-dash tui: {e}");
                std::process::exit(1);
            }
        }
        return Ok(());
    }

    if name == "export" {
        match monitor::export_headless() {
            Ok(stem) => println!("{stem}.json .yaml .md · page + json → ~/.watchdog/html"),
            Err(e) => {
                eprintln!("my-konsole-dash export: {e}");
                std::process::exit(1);
            }
        }
        return Ok(());
    }

    let mut dash: Box<dyn frame::Dashboard> = match name.as_str() {
        "monitor"  => Box::new(monitor::Monitor::new()),
        "stack"    => Box::new(stack::Stack::new()),
        "journal"  => Box::new(journal::Journal::new()),
        "cloud"    => Box::new(cloud::Cloud::new()),
        "datasync" => Box::new(datasync::DataSync::new()),
        "agi"      => Box::new(agi::Agi::new()),
        "devctl"   => Box::new(devctl::DevCtl::new()),
        other => {
            eprintln!("my-konsole-dash: unknown dashboard '{other}'");
            eprintln!("  usage: my-konsole-dash [monitor|stack|journal|cloud|datasync|agi|devctl]");
            eprintln!("         my-konsole-dash export   write the HTML report and exit");
            eprintln!("         my-konsole-dash tui [cols] [rows]   one screen as HTML, to stdout");
            std::process::exit(2);
        }
    };
    frame::run(dash.as_mut())
}
