#!/usr/bin/env bash
# Build the watchdog web panel: src/ (ts + scss) -> dist/ (plain html/css/js).
#
# dist/ is COMMITTED, not generated at deploy time. This panel's whole job is to
# be readable when the machine is in trouble, and a page that needs a toolchain
# to render is a page that is missing exactly when it is wanted. The compilers
# below are an optimisation on authoring, never a dependency of serving.
set -euo pipefail
cd "$(dirname "$0")"

if command -v sass >/dev/null 2>&1; then
  sass --no-source-map --style=expanded src/watchdog.scss dist/watchdog.css
  echo "[build] scss -> dist/watchdog.css"
else
  echo "[build] no sass; dist/watchdog.css left as committed"
fi

if command -v esbuild >/dev/null 2>&1; then
  esbuild src/watchdog.ts --outfile=dist/watchdog.js --format=iife --target=es2017
  echo "[build] ts -> dist/watchdog.js"
else
  echo "[build] no esbuild; dist/watchdog.js left as committed"
fi

# The offline fallback is a SAMPLE of this machine, refreshed only on request:
# regenerating it on every build would commit a new 40KB blob per build and
# quietly bake whatever this laptop happened to be doing into the repo.
if [ "${1:-}" = "--snapshot" ]; then
  snap="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/my-konsole-watchdog.json"
  if [ -r "$snap" ]; then
    {
      echo "// Offline fallback: the snapshot as a SCRIPT, not as data."
      echo "// A sibling .json cannot be fetch()ed from file:// -- CORS blocks it -- so the"
      echo "// same document is shipped as an assignment the page can simply <script> in."
      echo "// Regenerated by build.sh --snapshot; it is a sample, not the truth."
      printf 'window.__WATCHDOG_FALLBACK__ = '
      jq -c '{ts, cpu, load1, mem, swap, host_info, totals, docker_daemon, containers, images, listening: (.listening[0:20]), proc_table: (.proc_table[0:40]), pressure_cpu, pressure_io, pressure_memory}' "$snap"
      echo ";"
    } > dist/watchdog.js.json
    echo "[build] snapshot -> dist/watchdog.js.json"
  else
    echo "[build] no live snapshot at $snap; fallback left as committed" >&2
  fi
fi
