#!/bin/sh
# Container launcher — data-driven from containers.json
# Usage: ./containers.sh                    # interactive menu
#        ./containers.sh deb-nix cli        # direct
#        ./containers.sh 1                  # shortcode
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$SCRIPT_DIR/containers.json"

# Compose files generated by unix/ca_containers_user/build.sh
COMPOSE_DIR="${HOME}/git/cloud-unix/ca_containers_user/dist"

# ═══════════════════════════════════════════════════════════════════
# JSON HELPERS (jq required)
# ═══════════════════════════════════════════════════════════════════

_jq() { jq -r "$1" "$CONFIG"; }

# ═══════════════════════════════════════════════════════════════════
# MENU — generated from combinations[] in containers.json
# ═══════════════════════════════════════════════════════════════════

show_menu() {
  R='\033[0m'; C='\033[1;36m'; D='\033[0;90m'; W='\033[1;37m'
  printf "\n  ${C}Containers${R}\n"
  printf "  ${D}──────────────────────────────────${R}\n"

  _prev_image=""
  _jq '.combinations[] | "\(.id) \(.image) \(.label)"' | while read -r _id _img _label; do
    if [ "$_img" != "$_prev_image" ] && [ -n "$_prev_image" ]; then
      printf "  ${D}──────────────────────────────────${R}\n"
    fi
    printf "  ${W}%s${R}  %s\n" "$_id" "$_label"
    _prev_image="$_img"
  done

  printf "  ${D}──────────────────────────────────${R}\n"
  printf "  ${D}(b)ack  (q)uit${R}\n\n> "
  read -r _choice
  case "$_choice" in
    b|back) return 0 ;; q|quit) exit 0 ;;
    *)
      _match=$(_jq ".combinations[] | select(.id == ${_choice}) | \"\(.image) \(.profile)\"" 2>/dev/null || echo "")
      if [ -n "$_match" ]; then
        _img=$(echo "$_match" | cut -d' ' -f1)
        _prof=$(echo "$_match" | cut -d' ' -f2)
        do_run "$_img" "$_prof"
      else
        echo "Invalid choice: $_choice"; show_menu
      fi ;;
  esac
}

# ═══════════════════════════════════════════════════════════════════
# RUNTIME DETECTION
# ═══════════════════════════════════════════════════════════════════

detect_runtime() {
  DOCKER=""; RUNTIME=""
  if command -v docker >/dev/null 2>&1; then
    DOCKER="docker"; RUNTIME="docker"
  elif command -v podman >/dev/null 2>&1; then
    DOCKER="podman"; RUNTIME="podman"
  else
    echo "ERROR: No container runtime (docker/podman) found"; exit 1
  fi
}

# ═══════════════════════════════════════════════════════════════════
# RESOLVE — image URL from JSON
# ═══════════════════════════════════════════════════════════════════

resolve_image() {
  IMG=$(_jq ".images.\"$1\"")
  [ "$IMG" = "null" ] && { echo "Unknown image: $1"; exit 1; }
}

# ═══════════════════════════════════════════════════════════════════
# ENV EXPANSION — resolve ${VAR} in strings
# ═══════════════════════════════════════════════════════════════════

_expand() {
  eval "printf '%s' \"$1\"" 2>/dev/null || printf '%s' "$1"
}

# ═══════════════════════════════════════════════════════════════════
# BUILD MOUNTS — from profile.mounts[] with conditional checks
# ═══════════════════════════════════════════════════════════════════

build_mounts() {
  _profile="$1"
  MOUNTS=""
  _jq ".profiles.\"$_profile\".mounts[]" | while read -r _mount; do
    _expanded=$(_expand "$_mount")
    # Check conditional suffix: ?socket = must be a socket, ?dir = must be a dir
    case "$_expanded" in
      *"?socket")
        _path=$(echo "$_expanded" | sed 's/?socket$//' | cut -d: -f1)
        [ -S "$_path" ] && printf " -v %s" "$(echo "$_expanded" | sed 's/?socket$//')"
        ;;
      *"?dir")
        _path=$(echo "$_expanded" | sed 's/?dir$//' | cut -d: -f1)
        [ -d "$_path" ] && printf " -v %s" "$(echo "$_expanded" | sed 's/?dir$//')"
        ;;
      *)
        printf " -v %s" "$_expanded"
        ;;
    esac
  done
}

# ═══════════════════════════════════════════════════════════════════
# BUILD ENV — from profile.env{} merged with defaults
# ═══════════════════════════════════════════════════════════════════

build_env() {
  _profile="$1"
  _env=""
  _env="$_env -e HOME=${HOME:-/root} -e USER=${USER:-root}"
  _env="$_env -e PATH=$(_expand "$(_jq '.path')")"
  _jq ".profiles.\"$_profile\".env | to_entries[] | \"\(.key)=\(.value)\"" | while read -r _kv; do
    _expanded=$(_expand "$_kv")
    printf " -e %s" "$_expanded"
  done
  printf "%s" "$_env"
}

# ═══════════════════════════════════════════════════════════════════
# BANNER (shown inside container after launch)
# ═══════════════════════════════════════════════════════════════════

mk_banner() {
  _variant="$1"; _profile="$2"
  _HELLO='
R="\033[0m"; C="\033[1;36m"; B="\033[1;34m"; M="\033[1;35m"; W="\033[1;37m"; D="\033[0;90m"; Y="\033[1;33m"; G="\033[1;32m"
printf "\n"
printf "${C}  ██████╗ ${B}████████╗${M}██╗  ██╗${R}\n"
printf "${C}  ██╔══██╗${B}╚══██╔══╝${M}██║ ██╔╝${R}\n"
printf "${C}  ██║  ██║${B}   ██║   ${M}█████╔╝ ${R}  ${W}Diego'\''s Container${R}\n"
printf "${C}  ██║  ██║${B}   ██║   ${M}██╔═██╗ ${R}  ${D}Profile: PROFILE_PLACEHOLDER${R}\n"
printf "${C}  ██████╔╝${B}   ██║   ${M}██║  ██╗${R}\n"
printf "${C}  ╚═════╝ ${B}   ╚═╝   ${M}╚═╝  ╚═╝${R}\n"
printf "\n"
_h=$(hostname -s 2>/dev/null || echo "?")
_os=$(cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d "\"" || uname -s)
_arch=$(uname -m 2>/dev/null || echo "?")
_kern=$(uname -r 2>/dev/null || echo "?"); _kern=${_kern%%[-+]*}
_cpu=$(nproc 2>/dev/null || echo "?")
_ram=$(awk "/MemTotal/{printf \"%d\", \$2/1024}" /proc/meminfo 2>/dev/null || echo "?")
_nix="off"; command -v nix >/dev/null 2>&1 && _nix="${G}ON${R}"
_dk="off"; command -v docker >/dev/null 2>&1 && _dk="${G}ON${R}"
printf "  ${Y}host${R}  ${W}%-20s${R}  ${Y}os${R}    ${W}%s${R}\n" "$_h" "$_os"
printf "  ${Y}arch${R}  ${W}%-20s${R}  ${Y}kernel${R}  ${W}%s${R}\n" "$_arch" "$_kern"
printf "  ${Y}cpu${R}   ${W}%-20s${R}  ${Y}ram${R}     ${W}%sMB${R}\n" "$_cpu cores" "$_ram"
printf "  ${Y}nix${R}   $_nix                        ${Y}docker${R}  $_dk\n"
printf "  ${D}──────────────────────────────────────────────${R}\n"
printf "\n"
'
  _HELLO=$(printf '%s' "$_HELLO" | sed "s/PROFILE_PLACEHOLDER/$_variant \/ $_profile/")

  # Image metadata
  _IMG_SIZE=$("$DOCKER" image inspect "$IMG" --format '{{.Size}}' 2>/dev/null || echo "0")
  _IMG_SIZE_MB=$(( _IMG_SIZE / 1024 / 1024 ))
  _IMG_CREATED=$("$DOCKER" image inspect "$IMG" --format '{{.Created}}' 2>/dev/null | cut -c1-10 || echo "?")
  _IMG_ARCH=$("$DOCKER" image inspect "$IMG" --format '{{.Architecture}}' 2>/dev/null || echo "?")
  _lbl() { _v=$("$DOCKER" image inspect "$IMG" --format "{{index .Config.Labels \"$1\"}}" 2>/dev/null); [ "$_v" != "<no value>" ] && [ -n "$_v" ] && echo "$_v" || echo "$2"; }
  _IMG_DIGEST=$("$DOCKER" image inspect "$IMG" --format '{{index .RepoDigests 0}}' 2>/dev/null | sed 's/.*@//' | cut -c1-19 || echo "?")
  _IMG_LAYERS=$("$DOCKER" image inspect "$IMG" --format '{{len .RootFS.Layers}}' 2>/dev/null || echo "?")
  _IMG_SRC=$(_lbl "org.opencontainers.image.source" "github.com/diegonmarcos/cloud-unix")
  _IMG_DESC=$(_lbl "org.opencontainers.image.description" "Nix dev env")
  _IMG_DFILE=$(_lbl "diego.image.dockerfile.path" "Containerfile")
  _IMG_COMPOSE=$(_lbl "diego.image.compose.path" "compose.yaml")
  _IMG_FLAKE=$(_lbl "diego.image.flake.path" "ba_flakes_desktop/src/")
  _IMG_GHCR=$(_lbl "diego.image.ghcr" "$IMG")
  _IMG_RUNNER=$(_lbl "diego.image.runner" "containers.sh")
  _IMG_SHELL=$(_lbl "diego.image.packages.shell" "fish starship eza bat fd rg fzf jq")
  _IMG_LANG=$(_lbl "diego.image.packages.lang" "rust go node python ruby gcc llvm")
  _IMG_CLOUD=$(_lbl "diego.image.packages.cloud" "docker kubectl helm terraform sops age")
  _IMG_META=$(_lbl "diego.image.container.path" "~/.image-meta/")

  _HELLO="${_HELLO}
printf \"  \${Y}image\${R} \${W}%-20s\${R}  \${Y}size\${R}    \${W}%sMB\${R}\n\" \"$_IMG_ARCH\" \"$_IMG_SIZE_MB\"
printf \"  \${Y}built\${R} \${W}%-20s\${R}  \${Y}tag\${R}     \${W}%s\${R}\n\" \"$_IMG_CREATED\" \"latest\"
printf \"  \${Y}layers\${R}\${W}%-19s\${R}  \${Y}digest\${R}  \${W}%s\${R}\n\" \" $_IMG_LAYERS\" \"$_IMG_DIGEST\"
printf \"  \${D}──────────────────────────────────────────────\${R}\n\"
printf \"  \${Y}ghcr\${R}      \${W}%s\${R}\n\" \"$_IMG_GHCR\"
printf \"  \${Y}src\${R}       \${W}%s\${R}\n\" \"$_IMG_SRC\"
printf \"  \${Y}flake\${R}     \${W}%s\${R}\n\" \"$_IMG_FLAKE\"
printf \"  \${Y}file\${R}      \${D}%s\${R}\n\" \"$_IMG_DFILE\"
printf \"  \${Y}compose\${R}   \${D}%s\${R}\n\" \"$_IMG_COMPOSE\"
printf \"  \${Y}embedded\${R}  \${D}%s\${R}\n\" \"$_IMG_META\"
printf \"  \${Y}runner\${R}    \${D}%s\${R}\n\" \"$_IMG_RUNNER\"
printf \"  \${D}──────────────────────────────────────────────\${R}\n\"
printf \"  \${Y}shell\${R}     \${D}%s\${R}\n\" \"$_IMG_SHELL\"
printf \"  \${Y}lang\${R}      \${D}%s\${R}\n\" \"$_IMG_LANG\"
printf \"  \${Y}cloud\${R}     \${D}%s\${R}\n\" \"$_IMG_CLOUD\"
printf \"  \${D}──────────────────────────────────────────────\${R}\n\"
printf \"  \${D}%s\${R}\n\" \"$_IMG_DESC\"
printf \"\n\"
"
  BANNER="$_HELLO"
}

# ═══════════════════════════════════════════════════════════════════
# RUN — assemble docker run from JSON profile data
# ═══════════════════════════════════════════════════════════════════

SYS_HOSTNAME=$(hostname -s 2>/dev/null || echo "container")

do_run() {
  _variant="$1"; _profile="$2"; _extra="${3:-}"

  # Normalize legacy names
  case "$_variant" in
    diego-cli|diego-gui|diego-tty)
      _profile=$(echo "$_variant" | sed 's/diego-//')
      _variant="deb-nix" ;;
  esac

  detect_runtime
  resolve_image "$_variant"

  # Read profile config from JSON
  _container_name=$(_jq ".profiles.\"$_profile\".container_name")
  _interactive=$(_jq ".profiles.\"$_profile\".interactive")
  if [ "$RUNTIME" = "podman" ]; then
    _flags=$(_jq ".profiles.\"$_profile\".podman_flags")
  else
    _flags=$(_jq ".profiles.\"$_profile\".flags")
  fi

  echo "=== docker-run [$_profile]: $IMG ==="
  "$DOCKER" pull "$IMG"

  mk_banner "$_variant" "$_profile"

  # Build mounts and env from JSON
  _mounts=$(build_mounts "$_profile")
  _env=$(build_env "$_profile")

  # Shell command
  if [ "$_interactive" = "true" ]; then
    _it_flag="-it"
    _shell_cmd="${BANNER}
exec fish 2>/dev/null || exec bash 2>/dev/null || exec sh"
  else
    _it_flag=""
    _shell_cmd="${BANNER}
${_extra:-bash}"
  fi

  # Run
  "$DOCKER" run $_it_flag --rm \
    --name "$_container_name" \
    --hostname "${SYS_HOSTNAME}-${_profile}" \
    $_flags $_mounts $_env \
    -w "${HOME:-/root}" \
    "$IMG" bash -c "$_shell_cmd"
}

# ═══════════════════════════════════════════════════════════════════
# ENTRY POINT — shortcodes from combinations[], or named args
# ═══════════════════════════════════════════════════════════════════

case "${1:-}" in
  "")  show_menu ;;
  [0-9]*)
    _match=$(_jq ".combinations[] | select(.id == ${1}) | \"\(.image) \(.profile)\"" 2>/dev/null || echo "")
    if [ -n "$_match" ]; then
      do_run $(echo "$_match") "${2:-}"
    else
      echo "Invalid shortcode: $1"; exit 1
    fi ;;
  deb-nix|deb-apt) do_run "$1" "${2:-cli}" "${3:-}" ;;
  *)   echo "Usage: $0 [1-$(_jq '.combinations | length') | deb-nix|deb-apt cli|gui|tty]"; exit 1 ;;
esac
