#!/bin/sh
# 23b — Install Fish + fetch configs (NO sudo, NO tool install, graceful errors)
# Works in unprivileged containers, shared servers, rootless environments
set -u

FISH_DIR="${HOME}/.config/fish"
STARSHIP_DIR="${HOME}/.config"
RAW="https://raw.githubusercontent.com/diegonmarcos/cloud-unix/main/ba_flakes_desktop/src/modules/programs/shells/fish"

echo "=== Fish Shell Setup — lightweight (23b) ==="

# ═══════════════════════════════════════════════════════════════════
# STEP 1: Check/install Fish (no sudo — try user-level only)
# ═══════════════════════════════════════════════════════════════════

echo ""
echo "── Step 1: Fish Shell ──"
if command -v fish >/dev/null 2>&1; then
    echo "[OK] Fish installed: $(fish --version 2>/dev/null)"
else
    echo "[+] Attempting to install fish without sudo..."
    if command -v nix-env >/dev/null 2>&1; then
        nix-env -iA nixpkgs.fish 2>/dev/null \
            && echo "[OK] Fish installed via nix" \
            || echo "[!] nix-env install failed"
    elif command -v brew >/dev/null 2>&1; then
        brew install fish 2>/dev/null \
            && echo "[OK] Fish installed via brew" \
            || echo "[!] brew install failed"
    elif command -v conda >/dev/null 2>&1; then
        conda install -y -c conda-forge fish 2>/dev/null \
            && echo "[OK] Fish installed via conda" \
            || echo "[!] conda install failed"
    elif command -v cargo >/dev/null 2>&1; then
        echo "[!] Fish cannot be installed via cargo"
    else
        echo "[!] No user-level package manager found (nix/brew/conda)"
        echo "[!] Ask admin to: apt install fish / dnf install fish"
        echo "[!] Continuing with config deploy (fish may be installed later)..."
    fi
fi

# ═══════════════════════════════════════════════════════════════════
# STEP 2: Try to set as default shell (may fail without sudo)
# ═══════════════════════════════════════════════════════════════════

echo ""
echo "── Step 2: Default shell ──"
if command -v fish >/dev/null 2>&1; then
    FISH_PATH=$(command -v fish)
    CURRENT_SHELL=$(getent passwd "$(whoami)" 2>/dev/null | cut -d: -f7 || echo "")
    if [ "$CURRENT_SHELL" = "$FISH_PATH" ]; then
        echo "[OK] Already default: $FISH_PATH"
    else
        chsh -s "$FISH_PATH" 2>/dev/null \
            && echo "[OK] Default shell: fish" \
            || echo "[!] Cannot chsh (no sudo) — start fish manually or add to .bashrc: exec fish"
    fi
else
    echo "[!] Fish not found — skipping default shell"
fi

# ═══════════════════════════════════════════════════════════════════
# STEP 3: Skip if HM-managed
# ═══════════════════════════════════════════════════════════════════

if [ -L "$FISH_DIR/config.fish" ]; then
    echo "[OK] Fish config managed by home-manager — skipping"
    exit 0
fi
mkdir -p "$FISH_DIR/functions" "$FISH_DIR/conf.d" "$FISH_DIR/completions" 2>/dev/null || true

# ═══════════════════════════════════════════════════════════════════
# STEP 4: Generate config.fish with fallback aliases
# ═══════════════════════════════════════════════════════════════════

echo ""
echo "── Step 4: Fish config ──"

cat > "$FISH_DIR/config.fish" << 'FISHCONF'
# Generated by dtk.sh 23b — lightweight non-HM config (no sudo install)
if status is-interactive
    # Modern CLI with fallbacks (tools may or may not be installed)
    if command -q eza
        alias ls="eza --color=auto --icons"
        alias ll="eza -alF --icons"
        alias la="eza -A --icons"
        alias l="eza -CF --icons"
        alias lh="eza -lh --icons"
        alias lt="eza --tree --level=2 --icons"
    else
        alias ls="command ls --color=auto"
        alias ll="command ls -alF --color=auto"
        alias la="command ls -A --color=auto"
        alias l="command ls -CF --color=auto"
        alias lh="command ls -lh --color=auto"
        alias lt="tree -L 2 2>/dev/null; or command ls -R"
    end
    if command -q bat;    alias cat="bat --paging=never"; end
    if command -q rg;     alias grep="rg"; end
    if command -q fd;     alias find="fd"; end
    if command -q duf;    alias df="duf";  else; alias df="command df -h"; end
    if command -q ncdu;   alias du="ncdu"; else; alias du="command du -sh"; end

    # Navigation
    alias ..="cd .."; alias ...="cd ../.."; alias ....="cd ../../.."

    # Safety
    alias rm="rm -i"; alias cp="cp -i"; alias mv="mv -i"

    # Python
    if command -q python3; alias py="python3"; alias python="python3"; end
    if command -q pip3;    alias pip="pip3"; end

    # System
    alias free="free -h 2>/dev/null; or true"
    alias ports="ss -tulanp 2>/dev/null; or netstat -tulanp 2>/dev/null; or true"
    alias myip="curl -s ifconfig.me 2>/dev/null; or echo offline"

    # Misc
    alias c="clear"; alias cls="clear"; alias h="history"
    alias path="echo \$PATH | tr ':' '\\n'"
    alias reload="source ~/.config/fish/config.fish"

    # Custom tools
    alias dtk="bash ~/git/cloud-mykonsole-dtk/dtk.sh"

    # Git abbreviations
    if command -q git
        abbr -a gs "git status -sb"; abbr -a ga "git add"; abbr -a gaa "git add --all"
        abbr -a gc "git commit"; abbr -a gcm "git commit -m"
        abbr -a gp "git push"; abbr -a gpl "git pull"; abbr -a gcl "git clone"
        abbr -a gl "git log --oneline --graph --decorate -20"
        abbr -a gd "git diff"; abbr -a gco "git checkout"
    end

    # Docker abbreviations
    if command -q docker
        abbr -a dps "docker ps"; abbr -a dpsa "docker ps -a"
        abbr -a dcu "docker compose up"; abbr -a dcd "docker compose down"
    end

    # PATH
    fish_add_path -m ~/.cargo/bin ~/.npm-global/bin ~/go/bin ~/.local/bin ~/.nix-profile/bin

    # Integrations (only if installed)
    if command -q starship; starship init fish | source; end
    if command -q zoxide;   zoxide init fish | source; end
    if command -q fzf;      fzf --fish | source; end
    if command -q direnv;   direnv hook fish | source; end
end
FISHCONF
echo "[OK] config.fish"

# ═══════════════════════════════════════════════════════════════════
# STEP 5: Fetch functions from unix repo
# ═══════════════════════════════════════════════════════════════════

echo "[+] Fetching fish functions..."
if ! command -v curl >/dev/null 2>&1; then
    echo "[!] curl not found — cannot fetch functions"
else
    FUNCS_URL="$RAW/functions"
    _fetched=0; _missed=0
    for fn in fish_greeting ai-cli cloud-ai-cli gacp gcam gpsh git_current_branch \
              extract mkcd mkd serve hhelp myhelp localip duh backup cpucap qfind \
              hg fish-e fish-e-stop __fzf_search_commands; do
        _body_tmp=$(mktemp)
        if curl -sfL "$FUNCS_URL/${fn}.fish" -o "$_body_tmp" 2>/dev/null && [ -s "$_body_tmp" ]; then
            { echo "function $fn"; sed 's/^/  /' "$_body_tmp"; echo "end"; } > "$FISH_DIR/functions/${fn}.fish"
            _fetched=$((_fetched + 1))
        else
            _missed=$((_missed + 1))
        fi
        rm -f "$_body_tmp"
    done
    echo "[OK] $_fetched functions fetched, $_missed missed"
fi

# ═══════════════════════════════════════════════════════════════════
# STEP 6: Starship config
# ═══════════════════════════════════════════════════════════════════

mkdir -p "$STARSHIP_DIR" 2>/dev/null || true
cat > "$STARSHIP_DIR/starship.toml" << 'STAR'
format = "$username$hostname$directory$git_branch$git_status$cmd_duration$line_break$character"
[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
[directory]
truncation_length = 3
[git_branch]
format = "[$branch]($style) "
[cmd_duration]
min_time = 2000
STAR
echo "[OK] starship.toml"

echo ""
echo "=== Done ==="
echo "  ~/.config/fish/config.fish"
echo "  ~/.config/fish/functions/ ($(ls "$FISH_DIR/functions/" 2>/dev/null | wc -l) files)"
echo "  ~/.config/starship.toml"
echo ""
if command -v fish >/dev/null 2>&1; then
    echo "Run: source ~/.config/fish/config.fish"
else
    echo "Fish not installed yet. Once installed, run: fish"
fi
