# my-browser-rust-chromium — packaged from CI's prebuilt release tarball.
#
# HARD CONSTRAINT: this does NOT build CEF/Chromium in Nix. build.sh (CI) is
# the only compiler in this project — cargo build against a cloned cef-rs +
# `export-cef-dir`'d libcef, packaged by `build.sh release` into a tarball and
# published to the rolling GitHub release tag "my-browser-rust-chromium-latest"
# (see build.sh: release/gh-release verbs, $TARBALL). This file only unpacks
# that tarball and patches it to run under NixOS's non-FHS /lib linking.
#
# The hash lives in ./tarball-hash.nix, regenerated by `build.sh nix-hash`
# (it streams the published tarball into sha256sum, so a ~366MB artifact never
# touches this near-full disk or the nix store).
#
# HAZARD, read before trusting a build: the URL points at a ROLLING tag. Every
# ship run replaces the tarball at that same URL, so this pinned hash goes stale
# the moment CI publishes again, and the next fetch fails with a hash mismatch —
# noisy, but at least never silently wrong. Re-run `build.sh nix-hash` and commit
# after each release.
# ponytail: the real fix is an immutable per-release tag (…-v<short-sha>) pinned
# here alongside the hash, so an old checkout keeps building. That is a change to
# the release scheme, not to this file, so it is deliberately not made here.
{ pkgs, lib ? pkgs.lib }:

let
  name = "my-browser-rust-chromium";
  # Rolling release — see build.sh TAG="${NAME}-latest" and $TARBALL.
  version = "latest";
  tarballName = "${name}-linux-x86_64.tar.gz";

  configsDir = ../../2_configs;

  src = pkgs.fetchurl {
    # The release lives on the monorepo, not a per-app repo: build.sh ships it to
    # the rolling tag "${name}-latest" on cloud-u-linux itself.
    url = "https://github.com/diegonmarcos/cloud-u-linux/releases/download/${name}-latest/${tarballName}";
    sha256 = import ./tarball-hash.nix;
  };
in
pkgs.stdenv.mkDerivation {
  pname = name;
  inherit version src;

  nativeBuildInputs = [ pkgs.autoPatchelfHook pkgs.makeWrapper ];

  # Runtime deps a CEF/Chromium OSR binary links against. Trimmed to what
  # Chromium-family binaries commonly need; autoPatchelfHook will complain
  # (build failure, not silent) about anything still missing.
  buildInputs = with pkgs; [
    glib nss nspr
    xorg.libX11 xorg.libXcomposite xorg.libXdamage xorg.libXrandr
    xorg.libXext xorg.libXfixes xorg.libXrender xorg.libxcb xorg.libXtst
    xorg.libXi xorg.libXScrnSaver xorg.libxshmfence
    wayland libxkbcommon
    libGL mesa
    alsa-lib
    dbus
    expat
    fontconfig freetype
    at-spi2-atk at-spi2-core
    cups
    libdrm
    pango cairo gtk3
    stdenv.cc.cc.lib
  ];

  # No unpackPhase override needed: fetchurl's .tar.gz is auto-unpacked by
  # the default unpackPhase. sourceRoot stays "." since the tarball's own
  # top level IS the bundle contents (build.sh: tar -C "$DIST/bundle" -czf).
  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall

    # Keep the whole bundle layout intact under $out/share/${name}: the
    # launcher, libcef.so, CEF resources and shell/ all resolve paths
    # relative to the launcher's own directory (see build.sh's generated
    # $DIST/bundle/my-browser: HERE="$(cd "$(dirname "$0")" && pwd)").
    bundleDir="$out/share/${name}"
    mkdir -p "$bundleDir"
    cp -r . "$bundleDir/"

    chmod +x "$bundleDir/my-browser" "$bundleDir/${name}"

    # NEVER setuid, and never route through CEF's chrome-sandbox helper — that
    # helper is setuid-root by design upstream, which we do not want to own
    # under Nix. Instead force --no-sandbox from a thin wrapper.
    # ponytail: security ceiling — no OS-level sandboxing of the renderer
    # process; relies on this being a single-purpose kiosk-ish browser rather
    # than a general-purpose multi-site daily driver. Upgrade path: wire up
    # bubblewrap/firejail around the wrapper, or a real (non-setuid) CEF
    # sandbox once cef-rs supports user-namespace sandboxing.
    mkdir -p "$out/bin"
    makeWrapper "$bundleDir/my-browser" "$out/bin/${name}" \
      --add-flags "--no-sandbox"

    # Icon + .desktop, substituting the real $out store path for @EXEC@.
    mkdir -p "$out/share/icons/hicolor/scalable/apps" "$out/share/applications"
    cp "${configsDir}/${name}.svg" "$out/share/icons/hicolor/scalable/apps/${name}.svg"
    substitute "${configsDir}/${name}.desktop" "$out/share/applications/${name}.desktop" \
      --replace "@EXEC@" "$out/bin/${name}"

    runHook postInstall
  '';

  # autoPatchelfHook needs to see the shared libs staged in $out already,
  # so it must run after installPhase (its default hook order does this
  # automatically as a fixupPhase step) — nothing extra to wire here beyond
  # listing it in nativeBuildInputs.

  meta = {
    description = "Rust (winit+wgpu) front-end + off-screen-rendered Chromium (CEF) backend — genuine Chrome TLS fingerprint, zero Google chrome UI";
    homepage = "https://github.com/diegonmarcos/cloud-u-linux";
    platforms = [ "x86_64-linux" ];
    mainProgram = name;
  };
}
